### ISSUE TITLE
integration with winner

### ISSUE THREAD

**Issue by chiply** [Javyre/winds.el#2]
Love this package by the way.

Not sure if you use winner, but there is a function in that package called winner-undo which undoes any changes to window configuration.  

Winner seems to recognize ws and cfg switching as things to undo, and can cause switches to the previous ws's layout while remaining in the currrent ws.  In my opinion, this shouldn't happen.  Is there a way to make sure that winner's undo steps are scoped to workspaces and cfgs?  If you're unfamiliar with winner, I can try to look into this and see if i can fix

**Comment by Javyre** [comment]
I use winner myself. I had noticed this issue ever since I used eyebrowse actually.
I ended up getting used to it and now don't notice it as much, but this is not an excuse.
This is an issue and could be considered a bug.

The only way I see of solving this is to have a separate winner window config history for each window config slot in `winds.el`. Making winner simply ignore window transformations I think would still make the global winner history incoherent. I need to think this over a bit, but that's my initial thought.

When I get the chance, I'll look into the `winner.el` source code.

**Comment by Javyre** [comment]
It turned out that reimplementing winner/tab-bar-mode history in winds from scratch was the easiest way out.

With the latest commit (https://github.com/Javyre/winds.el/commit/d5c13c321a9af03b025c200a03562047cbc5087c) `winds.el` pretty much becomes a full winner replacement.
